### PR TITLE
Fixed savanna plateaus :D

### PR DESCRIPTION
**Pull request by topisani**
Rewrote these two biomes completely. Also added a bit of noise to the clay colours
Savanna Plateau M:

Normal savanna Plateau:

Nice seed if anyone wants to test: 6961609752980674468

### CODE REVIEW

**Comment by topisani** [comment]
@KdotJPG or @Zeno410, could one of you take a look at my code and see if i am doing something ilegal anywhere? i got the sense this terrain code is extremely optimized, and thats not really my strong suit.

**Comment by topisani** [comment]
That might be an improvement

**Comment by Zeno410** [comment]
If you're just adding on noises that's as optimized as what I'm doing. Kdot did some experiments with simultaneous evaluation and it didn't help. I did some tests with older code and found noise evaluations were only 2% of cpu time so at present it's probably not a big issue.

**Comment by topisani** [comment]
im guessing this can be merged now? i think im done with savannas, they may get some love while im doing mesas

**Pull request merged**
